Repository Ivan-dela-cruz/challenge-git, pull requests merged in 2022-04, with the labels that each got.

#2 feat:(FILE) Agregar archivo tipo javascript
  helper.js
Labels: pull-request, Dp6Challengue

#4 feat:(FUNCTION) Crear funcion que para sumar 2 numeros
  helper.js
Labels: issue, Dp6Challengue

#6 feat:(FILE) add index.html with title and import style.css
  index.html
Labels: issue, pull-request

#8 feat:(FILE) add style.css Dp6Challengue issue
  styles.css
Labels: pull-request, Dp6Challengue

#13 feat:(APP-ALEXANDER) Create project with vue 2.0 for the auth with axios
  app-alexander/.gitignore
  app-alexander/README.md
  app-alexander/babel.config.js
  app-alexander/jsconfig.json
  app-alexander/package-lock.json
  app-alexander/package.json
  app-alexander/public/favicon.ico
  app-alexander/public/index.html
  app-alexander/src/App.vue
  app-alexander/src/assets/logo.png
  app-alexander/src/components/HelloWorld.vue
  app-alexander/src/main.js
  app-alexander/vue.config.js
Labels: pull-request, Dp6Challengue

#15 feat:(CREAR) Creacion del proyecto
  app3/.gitignore
  app3/README.md
  app3/babel.config.js
  app3/jsconfig.json
  app3/package-lock.json
  app3/package.json
  app3/public/favicon.ico
  app3/public/index.html
  app3/src/App.vue
  app3/src/assets/logo.png
  app3/src/components/HelloWorld.vue
  app3/src/main.js
  app3/vue.config.js
Labels: pull-request, Dp6Challengue

#16 feat:(APP-ALEXANDER) Design login html
  app-alexander/src/App.vue
  app-alexander/src/components/HelloWorld.vue
Labels: pull-request, Dp6Challengue

#18 (CREAR) Maquetacion de Login
  app3/src/App.vue
  app3/src/components/shared/loginUser.vue
Labels: pull-request, Dp6Challengue

#21 feat:(APP-ALEXANDER)Implementation login function
  app-alexander/src/components/HelloWorld.vue
  app-alexander/src/services/config.js
Labels: pull-request, Dp6Challengue
